service: audio-api

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs20.x
  region: ${env:REGION, 'us-east-2'}
  stage: ${opt:stage, 'dev'}
  memorySize: 512
  timeout: 30

  environment:
    REGION: ${env:REGION, 'us-east-2'}
    S3_BUCKET_NAME: ${env:S3_BUCKET_NAME}
    USER_POOL_ID: ${env:USER_POOL_ID}
    EVENT_BUS_NAME: ${opt:eventBusName, 'default'}

  httpApi:
    cors:
      allowedOrigins:
        - '*'
      allowedHeaders:
        - Content-Type
        - Authorization
      allowedMethods:
        - GET
        - POST
        - PUT
        - DELETE
        - OPTIONS
      maxAge: 600

    authorizers:
      cognitoAuthorizer:
        type: jwt
        identitySource: $request.header.Authorization
        issuerUrl: https://cognito-idp.${env:REGION, 'us-east-2'}.amazonaws.com/${env:USER_POOL_ID}
        audience:
          - ${env:USER_POOL_CLIENT_ID}

  iam:
    role:
      statements:
        # S3 permissions - user-scoped
        - Effect: Allow
          Action:
            - s3:PutObject
            - s3:GetObject
            - s3:HeadObject
            - s3:ListBucket
          Resource:
            - arn:aws:s3:::${env:S3_BUCKET_NAME}/users/*
            - arn:aws:s3:::${env:S3_BUCKET_NAME}

        # EventBridge permissions (optional)
        - Effect: Allow
          Action:
            - events:PutEvents
          Resource:
            - arn:aws:events:${env:REGION, 'us-east-2'}:${aws:accountId}:event-bus/default

plugins:
  - serverless-esbuild
  - serverless-offline

custom:
  esbuild:
    bundle: true
    minify: false
    sourcemap: true
    exclude:
      - aws-sdk
    target: node20
    platform: node
    concurrency: 10

functions:
  createSession:
    handler: src/handlers/createSession.handler
    events:
      - httpApi:
          method: POST
          path: /api/audio/sessions
          authorizer:
            name: cognitoAuthorizer

  presignChunk:
    handler: src/handlers/presignChunk.handler
    events:
      - httpApi:
          method: POST
          path: /api/audio/sessions/{sessionId}/chunks/presign
          authorizer:
            name: cognitoAuthorizer

  completeChunk:
    handler: src/handlers/completeChunk.handler
    events:
      - httpApi:
          method: POST
          path: /api/audio/sessions/{sessionId}/chunks/complete
          authorizer:
            name: cognitoAuthorizer

  upsertManifest:
    handler: src/handlers/upsertManifest.handler
    events:
      - httpApi:
          method: PUT
          path: /api/audio/sessions/{sessionId}/manifest
          authorizer:
            name: cognitoAuthorizer

  finalizeSession:
    handler: src/handlers/finalizeSession.handler
    events:
      - httpApi:
          method: POST
          path: /api/audio/sessions/{sessionId}/finalize
          authorizer:
            name: cognitoAuthorizer

resources:
  Outputs:
    AudioApiUrl:
      Description: Audio API Gateway endpoint URL
      Value:
        Fn::Sub: https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com
      Export:
        Name: ${self:service}-${self:provider.stage}-api-url
